### ISSUE TITLE
[TASK] Send / Receive Friend Request

### ISSUE THREAD

**Issue by dongjoocha** [swsnu/swppfall2022-team9#11]
### Detail
- Implement backend REST APIs to support sending and receiving FriendRequests.
- This will be implemented by FriendRequest "Pending", "Accepted", "Rejected" status.
- When sending / receiving is going on, always make sure 1. max one-chon invariant 2. read/write permission update is correctly handled.

### Checklist
- [x] Design
- [x] Implementation
- [ ] Testing
  - Unit Test

**Comment by notiona** [comment]
### Detail
- Implement backend REST APIs to support sending and receiving FriendRequests.
- This will be implemented by FriendRequest "Pending", "Accepted", "Rejected" status.
- When sending / receiving is going on, always make sure 1. max one-chon invariant 2. read/write permission update is correctly handled.

### Checklist
- [ ] Design
- [ ] Implementation
- [ ] Testing
  - Unit Test
