### ISSUE TITLE
[TASK] Model Management(testing server)

### ISSUE THREAD

**Issue by dongjoocha** [swsnu/swppfall2022-team9#12]
### Detail
- Create and manage Django models that are required for LinkLink
- List and field specifications of the model is specified in the class diagram of the Design & Planing Doc.

### Checklist
- [x] Design
- [x] Implementation
- [ ] Testing
  - Unit Test

**Comment by notiona** [comment]
### Detail
- Create and manage Django models that are required for LinkLink
- List and field specifications of the model is specified in the class diagram of the Design & Planing Doc.

### Checklist
- [ ] Design
- [ ] Implementation
- [ ] Testing
  - Unit Test
