### ISSUE TITLE
[TASK] Friend Request Token (api url)

### ISSUE THREAD

**Issue by dongjoocha** [swsnu/swppfall2022-team9#13]
### Detail
- Implement backend APIs to support friendRequestToken one-chon adding route.
- Both the url token parsing & friend request token validity check should take place.

### Checklist
- [x] Design
- [x] Implementation
- [x] Testing
  - Unit Test

**Comment by notiona** [comment]
### Detail
- Implement backend APIs to support friendRequestToken one-chon adding route.
- Both the url token parsing & friend request token validity check should take place.

### Checklist
- [ ] Design
- [ ] Implementation
- [ ] Testing
  - Unit Test
