### ISSUE TITLE
[TASK] Get Friend

### ISSUE THREAD

**Issue by dongjoocha** [swsnu/swppfall2022-team9#15]
### Detail
- Implement backend REST APIs that get list of one-chon and two-chon for a given user
- This API will be used in the graph visualization process in the frontend.

### Checklist
- [x] Design
- [x] Implementation
- [ ] Testing
  - Unit Test

**Comment by notiona** [comment]
### Detail
- Implement backend REST APIs that get list of one-chon and two-chon for a given user
- This API will be used in the graph visualization process in the frontend.

### Checklist
- [ ] Design
- [ ] Implementation
- [ ] Testing
  - Unit Test
