### ISSUE TITLE
[TASK] View Profile

### ISSUE THREAD

**Issue by dongjoocha** [swsnu/swppfall2022-team9#20]
### Detail
- Basic profile page that renders profile pictures, user information, list of 2-chons, etc. 
- Render slightly different pages based on whether the user is viewing his/her own profile, 1-chon's profile, or 2-chon's profile

### Checklist
- [ ] Design
- [ ] Implementation
- [ ] Testing
  - Unit Test

**Comment by JadenJSPark** [comment]
done
