### ISSUE TITLE
[TASK] Verify Email

### ISSUE THREAD

**Issue by dongjoocha** [swsnu/swppfall2022-team9#26]
### Detail
- Implement frontend page for verifying email for a user.
- Implement email verification APIs.

### Checklist
- [x] Design
- [x] Implementation
- [x] Testing
  - Unit Test

**Comment by notiona** [comment]
### Detail
- Implement frontend page for verifying email for a user.
- Implement email verification APIs.

### Checklist
- [ ] Design
- [ ] Implementation
- [ ] Testing
  - Unit Test
